### ISSUE TITLE
Please provide more detailed instructions

### ISSUE THREAD

**Issue by ghost** [jaroslav-kuchar/Multimode-Networks#1]
Jaroslav

I'm really keen to use your multimode-networks plugin, but I'm struggling to interpret your tutorial. Could you give more details on what this means:

Select Transformation represented by matrix (vertical and horizontal) dimension combination (eg. Person-Company x Company-Person -> Person-Person network)

What do you mean by matrix (vertical and horizontal) dimension combination? 

I have a two mode network with person (source) and topic (target). I want to reduce this to a person-person matrix. What should I expect to apply in the LHS and RHS matrix? 

Thanks

**Comment by jaroslav-kuchar** [comment]
The implementation of transformation is based on multiplication of matrices. That's the reason I mentioned it in the "tutorial". 

You can imagine it as normal matrix multiplication: 4x2 matrix multiplied by 2x4 matrix leads to 4x4 matrix.

If you have persons and topics and result should be person-person -> select person-topic x topic-person...
