### ISSUE TITLE
Attributes in csv files

### ISSUE THREAD

**Issue by dizandonorton** [jaroslav-kuchar/Multimode-Networks#2]
Hi Jaroslav Kuchar,
I'm trying to use your plugin but when I click on "Load attributes" button it doesn't show nothing.

My data was collected trought a csv file and it follow the following pattern:

[Note: Given A (a, b, c) the first part, B (1,2,3) the second. (It is a bipartite network)]

a, 1 (node "a" links to node "1")
a, 2 (node "a" links to node "2")
a, 3 (...)
b, 1 (...)
b, 2 (...)
c, 2 (...)
c, 3 (...)

Please help me to understand what are the attributes and how can I use/put them with a csv file?
If it's impossible then, what file format can I use to solve this?

Thanks in advance :-)

**Comment by jaroslav-kuchar** [comment]
Hi,
attributes are important to differentiate between groups (parts, node types) of nodes in your bipartite network. 
You can add new column ("attribute of node") in Data Laboratory and manualy label all your nodes. 
E.g. value of this column for nodes (a,b,c) will be A and value for (1,2,3) nodes will be B.
In this specific use case - the easiest way is Click on "Graph coloring" and then "Load attributes".

Jaroslav

**Comment by dizandonorton** [comment]
Many thanks Jaroslav Kuchar, it worked! But I still have one problem: 
- I don't know what is the layout algorithm that your plugin uses? 
- Or, is there any other layout algorithm for a bipartite network representation?

I used all of Gephi default algorithm and wasn't satisfied with the results (not intuitive graphs).
Thanks in advance.

**Comment by jaroslav-kuchar** [comment]
There is no layout implemented in my plugin - the nodes remain on the same positions. The layouts for bipartite networks in general are a bit difficult and they are not available in Gephi. I think, it is just matter of time before more appropriate layout will be available...After transformation - default algorithms should be enough...
